### PR TITLE
Add BungeeCord support

### PR DESCRIPTION
**Pull request by TheMiXeD**
With our Minecraft setup we are using BungeeCord.
It makes sense that BungeeCord does the authentication verification before letting a user go to one of the servers.
BungeeCord doesn't have the Bukkit dependencies so that plugin can't be used.

### CODE REVIEW

**Comment by dries007** [comment]
Oh wow, thanks!

**Comment by dries007** [comment]
Since I do not have a quick and easy way to set this, I'm going to assume it works and release a build with it. Where should I upload it to for the best reach?

**Comment by dries007** [comment]
@TheMiXeD If you'd like, use a recent build from https://jenkins.dries007.net/MCLink to verify everything works as you would expect.

**Comment by bartbuurmancom** [comment]
So far it does not work for me. I can log in as server owner, connected the server as instructed. Altho my test person could not login unsubbed but after subbing he could not join either, he recieved the kickMessage on both occasions. Server does register him. Used yesterdays  Bungeecord build.

**Comment by TheMiXeD** [comment]
Will have a look into that one

**Pull request merged**
